version: "3"

set: [nounset, errexit, pipefail]

tasks:
  default:
    silent: true
    cmd: task -l

  run:
    dir: codegen
    cmd: go run main.go

  gen:
    dir: example
    cmd: protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/greeter.proto

  server:
    dir: example
    cmd: go run server/server.go

  client:
    dir: example
    cmd: go run client/client.go
